services:
  - type: web
    name: lawlens-backend
    runtime: python
    buildCommand: pip install --only-binary=:all: -r requirements_render.txt || pip install -r requirements_render.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLASSIFICATION_MODEL
        value: Rohit171717/lawlens-classification
      - key: SUMMARIZATION_MODEL
        value: Rohit171717/lawlens-summarization
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
