services:
  - type: web
    name: lawlens-backend
    runtime: python
    buildCommand: bash build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLASSIFICATION_MODEL
        value: Rohit171717/lawlens-classification
      - key: SUMMARIZATION_MODEL
        value: Rohit171717/lawlens-summarization
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
