services:
  - type: web
    name: lawlens-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: CLASSIFICATION_MODEL
        sync: false
      - key: SUMMARIZATION_MODEL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
